### ISSUE TITLE
Argument discrepancies between run_pipeline.sh and commec wiki

### ISSUE THREAD

**Issue by brmagalis** [ibbis-screening/common-mechanism#10]
Line 21 of run_pipeline.sh still shows -p argument as reserved for number of processes.

**Comment by alexanian** [comment]
I think we should be using `commec screen` as opposed to `run_pipeline` by default, but the two should be in agreement with each other as long as we're maintaining both.

Investigating this caused me to notice that `processes` is not really an accurate way to describe how that argument is used; renamed to `jobs` and set up a new default in https://github.com/ibbis-screening/common-mechanism/pull/14

Will update the wiki once we release a new version.
