### ISSUE TITLE
check_reg_path.py

### ISSUE THREAD

**Issue by brmagalis** [ibbis-screening/common-mechanism#2]
The following warning is still being written:

/opt/src/check_reg_path.py:158: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

**Comment by alexanian** [comment]
I believe https://github.com/ibbis-screening/common-mechanism/pull/9/files#diff-4916d9ac4274b0d297035c36139991e13872a923b2f8b21f4cb3a9b5eb0d34e5R137-R141 should fix this. Hopefully you don't see the error after pulling down v0.1.2

**Comment by alexanian** [comment]
I'm not seeing this warning any more in my runs of v0.1.2, and used to see it, so I'm going to close this.
